services:
  - type: web
    name: paper-win-rock-game
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false  # Будем добавлять вручную в панели Render
    healthCheckPath: /
    autoDeploy: true
    plans:
      - name: free